name: E2E tests

on:
  workflow_dispatch:
  pull_request:
    branches: [development, main]
  push:
    branches: [development, main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # xvfb is needed so we can use MetaMask properly in our tests
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y fluxbox xvfb

      - name: Run xvfb and fluxbox
        run: Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: pnpm run hardhat:node, pnpm run prod:serve
          wait-on: "http://localhost:3000, http://localhost:8545"
          command: pnpm run test:e2e
        env:
          GNOSIS_RPC_URL: ${{ secrets.HARDHAT_ALCHEMY_ID }}
          FORK_BLOCK_NUMBER: 31453220
          NEXT_PUBLIC_QUICKNODE_API_KEY: ${{ secrets.NEXT_PUBLIC_QUICKNODE_API_KEY }}
          NEXT_PUBLIC_ALCHEMY_MAINNET_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_MAINNET_API_KEY }}
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          CYPRESS_BASE_URL: http://localhost:3000
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NEXT_PUBLIC_TEST_CONNECTOR: true

      - uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: tests/e2e/videos
          if-no-files-found: ignore
