name: E2E tests

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # xvfb is needed so we can use MetaMask properly in our tests
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y fluxbox xvfb

      - name: Run xvfb and fluxbox
        run: Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: pnpm run hardhat:chain, pnpm run prod
          # wait-on: "http://localhost:3000, http://localhost:8545"
        env:
          CYPRESS_BASE_URL: http://localhost:3000
